/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifceppd.redesensores.mom;

import com.ifceppd.redesensores.models.Cliente;
import com.ifceppd.redesensores.models.Sensor;
import javax.jms.Connection;
import javax.jms.ConnectionFactory;
import javax.jms.Destination;
import javax.jms.Message;
import javax.jms.MessageConsumer;
import javax.jms.MessageListener;
import javax.jms.ObjectMessage;
import javax.jms.Session;
import javax.swing.DefaultListModel;
import org.apache.activemq.ActiveMQConnection;
import org.apache.activemq.ActiveMQConnectionFactory;

/**
 *
 * @author elysson
 */
public class ClienteSubscriber extends javax.swing.JFrame {
    private Sensor s = null;
    
    /**
     * Creates new form Cliente
     */
    public ClienteSubscriber() {
        initComponents();
    }
    
    public ClienteSubscriber(Cliente c) throws Exception {
        initComponents();
        
        this.jLabelTitulo.setText(c.getNome() + " - Tópicos Assinados");
        
        DefaultListModel d = c.getSensores();
        Object[] lista = d.toArray();
        String topicName;
        
        for (Object s : lista) {
            topicName = s.toString();
            new Subscriber(topicName).Go();
        }

    }
    
    private class Subscriber implements MessageListener{
        /*
         * URL do servidor JMS. DEFAULT_BROKER_URL indica que o servidor está em localhost
        */	

        private static final String url = ActiveMQConnection.DEFAULT_BROKER_URL;

        private Session session;
        private MessageConsumer subscriber;
        private Connection connection;

        public Subscriber(String topicName) throws Exception{
            /*
             * Estabelecendo conexão com o Servidor JMS
            */		
            ConnectionFactory connectionFactory = new ActiveMQConnectionFactory(url);
            Connection connection = connectionFactory.createConnection();
            connection.start();

            /*
            * Criando Session 
            */
            Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);

            /*
            * Criando Topic
            */ 
            Destination dest = session.createTopic(topicName);

            /*
            * Criando Consumidor
            */
            MessageConsumer subscriber = session.createConsumer(dest);

            this.connection = connection;
            this.session = session;
            this.subscriber = subscriber;
        }

        public void Go(){

            try{
                /*
                * Setando Listener
                */
                subscriber.setMessageListener(this);

            }catch(Exception e){
                e.printStackTrace();
            }       
        }

        @Override
        public void onMessage(Message message) {
            if(message instanceof ObjectMessage){
                try{
                    ObjectMessage obj = (ObjectMessage) message;
                    Sensor s = (Sensor) obj.getObject();
                    String msg = "\n" + s.getNome() + ": " + s.getLeituraAtual();
                    
                    switch (s.getParamMonitor()) {
                        case "Temperatura":
                            jTextAreaTemp.setText(jTextAreaTemp.getText() + msg + " °C");
                            jTextAreaTemp.setCaretPosition(jTextAreaTemp.getText().length());
                            break;
                        case "Umidade":
                            jTextAreaUmid.setText(jTextAreaUmid.getText() + msg + " %");
                            jTextAreaUmid.setCaretPosition(jTextAreaUmid.getText().length());
                            break;
                        case "Velocidade":
                            jTextAreaVeloc.setText(jTextAreaVeloc.getText() + msg + " km/h");
                            jTextAreaVeloc.setCaretPosition(jTextAreaVeloc.getText().length());
                            break;
                        default:
                            break;
                    }
                }catch(Exception e){
                }
            }
        }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTemp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaUmid = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaVeloc = new javax.swing.JTextArea();
        jLabelUnd1 = new javax.swing.JLabel();
        jLabelUnd2 = new javax.swing.JLabel();
        jLabelUnd3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Nome do cliente");

        jTextAreaTemp.setEditable(false);
        jTextAreaTemp.setColumns(15);
        jTextAreaTemp.setRows(5);
        jScrollPane1.setViewportView(jTextAreaTemp);

        jTextAreaUmid.setEditable(false);
        jTextAreaUmid.setColumns(15);
        jTextAreaUmid.setRows(5);
        jScrollPane2.setViewportView(jTextAreaUmid);

        jTextAreaVeloc.setEditable(false);
        jTextAreaVeloc.setColumns(15);
        jTextAreaVeloc.setRows(5);
        jScrollPane3.setViewportView(jTextAreaVeloc);

        jLabelUnd1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUnd1.setText("Sensores de temperatura:");

        jLabelUnd2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUnd2.setText("Sensores de umidade:");

        jLabelUnd3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUnd3.setText("Sensores de velocidade:");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabelUnd1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabelUnd3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUnd2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUnd1)
                    .addComponent(jLabelUnd2)
                    .addComponent(jLabelUnd3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6))
        );

        getContentPane().add(jPanelPrincipal);
        jPanelPrincipal.setBounds(0, 0, 610, 310);

        setBounds(0, 0, 629, 351);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteSubscriber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteSubscriber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteSubscriber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteSubscriber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteSubscriber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUnd1;
    private javax.swing.JLabel jLabelUnd2;
    private javax.swing.JLabel jLabelUnd3;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaTemp;
    private javax.swing.JTextArea jTextAreaUmid;
    private javax.swing.JTextArea jTextAreaVeloc;
    // End of variables declaration//GEN-END:variables
}
