/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifceppd.redesensores.cadastros;

import com.ifceppd.redesensores.RedeSensoresExec;
import com.ifceppd.redesensores.models.Sensor;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author elysson
 */
public class SensorCadastro extends javax.swing.JFrame {
    
    private RedeSensoresExec pai = null;
    private String unidade = null;
    /**
     * Creates new form Cliente
     */
    public SensorCadastro() {
        initComponents();
    }
    
    public SensorCadastro(RedeSensoresExec pPai) {
        this.pai = pPai;
        initComponents();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.jLabelImg.setIcon(null);
        this.unidade = "Und";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jComboBoxParam = new javax.swing.JComboBox<>();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        limiteMin = new javax.swing.JLabel();
        limiteMax = new javax.swing.JLabel();
        jSpinnerMin = new javax.swing.JSpinner();
        jSpinnerMax = new javax.swing.JSpinner();
        jLabelUnd = new javax.swing.JLabel();
        jLabelUnd2 = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxParam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecione -", "Temperatura", "Umidade", "Velocidade" }));
        jComboBoxParam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxParamItemStateChanged(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTitulo.setText("Novo sensor");

        jLabelTipo.setText("Parâmetro monitorado:");

        limiteMin.setText("Limite mínimo:");

        limiteMax.setText("Limite máximo:");

        jSpinnerMin.setModel(new javax.swing.SpinnerNumberModel(0, -90, 250, 1));
        jSpinnerMin.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerMin, ""));
        jSpinnerMin.setEnabled(false);

        jSpinnerMax.setModel(new javax.swing.SpinnerNumberModel(0, -90, 250, 1));
        jSpinnerMax.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerMax, ""));
        jSpinnerMax.setEnabled(false);

        jLabelUnd.setText("Und.");

        jLabelUnd2.setText("Und.");

        jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVelocidade.png"))); // NOI18N

        jLabelNome.setText("Nome do equipamento:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabelImg))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(limiteMin)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerMin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(limiteMax)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerMax, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTipo)
                                    .addComponent(jLabelNome))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxParam, 0, 105, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNome))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUnd)
                            .addComponent(jLabelUnd2)))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButtonSalvar)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jComboBoxParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limiteMin)
                    .addComponent(jSpinnerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limiteMax)
                    .addComponent(jSpinnerMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnd2))
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabelImg)
                .addContainerGap())
        );

        getContentPane().add(jPanelPrincipal);
        jPanelPrincipal.setBounds(0, 0, 320, 360);

        setBounds(0, 0, 336, 398);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        String nome = this.jTextFieldNome.getText();
        String param = this.jComboBoxParam.getSelectedItem().toString();
        String min = this.jSpinnerMin.getValue().toString();
        String max = this.jSpinnerMax.getValue().toString();
        
        int limMin = Integer.parseInt(min);
        int limMax = Integer.parseInt(max);
        boolean valido = false;
        Sensor s = null;
        
        if(!nome.isEmpty() && !param.equals("- Selecione -") && limMax > limMin){
            valido = true;
            s = new Sensor(nome, param, limMin, limMax);
        }else{
            JOptionPane.showMessageDialog(this, "Verifique o nome, parâmetro monitorado "
                    + "ou valores dos limites", "Tente novamente!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.pai.criarSensor(s);
        
        this.dispose();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxParamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxParamItemStateChanged
        // TODO add your handling code here:
        this.jSpinnerMin.setEnabled(true);
        this.jSpinnerMax.setEnabled(true);
        
        switch (this.jComboBoxParam.getSelectedItem().toString()) {
            case "Temperatura":
                this.unidade = "°C";
                this.jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgTemperatura.jpg")));
                break;
            case "Umidade":
                this.unidade = "%";
                this.jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgUmidade.png")));
                break;
            case "Velocidade":
                this.unidade = "km/h";
                this.jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVelocidade.png")));
                break;
            default:
                this.unidade = "Und";
                this.jLabelImg.setIcon(null);
                this.jSpinnerMin.setEnabled(false);
                this.jSpinnerMax.setEnabled(false);
                break;
        }
        this.jLabelUnd.setText(unidade);
        this.jLabelUnd2.setText(unidade);
    }//GEN-LAST:event_jComboBoxParamItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SensorCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SensorCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SensorCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SensorCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SensorCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxParam;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUnd;
    private javax.swing.JLabel jLabelUnd2;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JSpinner jSpinnerMax;
    private javax.swing.JSpinner jSpinnerMin;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JLabel limiteMax;
    private javax.swing.JLabel limiteMin;
    // End of variables declaration//GEN-END:variables
}
